language: php

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

matrix:
  include:
    - dist: focal
      php: 8.2
      env: LIBONIG_INSTALL=1

  fast_finish: true

  allow_failures:
  - php: nightly

before_install:
  - if [ -n "$LIBONIG_INSTALL" ]; then sudo apt-get install libonig5; fi
  - composer self-update

install:
  - composer install --prefer-dist
  - scripts/ci-install.sh

deploy:
  provider: script
  script: scripts/deploy.sh
  skip_cleanup: false
  on:
    tags: true
    condition: "$TRAVIS_PHP_VERSION = 8.2"

script:
  - composer test
  - composer lint
