version: '3.4'

services:
  shop-validation-php-fpm:
    container_name: shop-validation-php-fpm
    build:
      context: ./
      dockerfile: ./docker/php/Dockerfile
      target: image-ci-testing
    ports:
      - "30102:80"
    volumes:
      - ./:/var/www/project
